apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elastic-operator
  namespace: elastic-system
subjects:
  - kind: ServiceAccount
    name: elastic-operator
    namespace: elastic-system
roleRef:
  kind: Role
  name: elastic-operator
  apiGroup: rbac.authorization.k8s.io
