apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internet-egress
  namespace: observability
spec:
  podSelector:
    matchLabels:
      app: elasticsearch
  policyTypes:
    - Egress

  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
