apiVersion: argocd.argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd

spec:
  project: observability

  source:
    repoURL: 'https://github.com/yasernoorollahi/platform.git'
    targetRevision: main
    path: components/elasticsearch/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
