apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: elasticsearch-network
  namespace: observability
spec:
  podSelector:
    matchLabels:
      app: elasticsearch

  policyTypes:
    - Ingress
    - Egress

  ingress:
    # 1️⃣ ES ↔ ES (transport + http)
    - from:
        - podSelector:
            matchLabels:
              app: elasticsearch
      ports:
        - protocol: TCP
          port: 9300
        - protocol: TCP
          port: 9200

    # 2️⃣ kubelet readiness / liveness probe
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata-name: kube-system
      ports:
        - protocol: TCP
          port: 9200

    # 3️⃣ future: Kibana / Ingress
    - from:
        - namespaceSelector:
            matchLabels:
              purpose: observability
      ports:
        - protocol: TCP
          port: 9200

  egress:
    # 4️⃣ DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata-name: kube-system
      ports:
        - protocol: UDP
          port: 53

    # 5️⃣ ES ↔ ES
    - to:
        - podSelector:
            matchLabels:
              app: elasticsearch
      ports:
        - protocol: TCP
          port: 9300
        - protocol: TCP
          port: 9200

    # 6️⃣ ECK operator
    - to:
        - namespaceSelector:
            matchLabels:
              control-plane: eck
      ports:
        - protocol: TCP
          port: 443
